/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux vhg1 2.6.32.12-0.7-pae #1 SMP 2010-05-20 11:14:20 +0200 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Tue Sep 29 17:55:27 CST 2015"
#define BUILD_ENV_SRCDIR "./"
#define BUILD_ENV_BUILDDIR "./"
#define BUILD_ENV_USER "luokunling"
#define BUILD_ENV_HOST "vhg1"
#define BUILD_ENV_COMPILER "/home/luokunling/open-HG633/BR-R5-HG633HG658v2-20140408/output/host/usr/bin/ccache"
#endif /* _BUILD_ENV_H */
