/* Driver for USB Mass Storage compliant devices
 *
 * Current development and maintenance by:
 *   (c) 1999-2003 Matthew Dharm (mdharm-usb@one-eyed-alien.net)
 *
 * Developed with the assistance of:
 *   (c) 2000 David L. Brown, Jr. (usb-storage@davidb.org)
 *   (c) 2003-2009 Alan Stern (stern@rowland.harvard.edu)
 *
 * Initial work by:
 *   (c) 1999 Michael Gee (michael@linuxspecific.com)
 *
 * usb_device_id support by Adam J. Richter (adam@yggdrasil.com):
 *   (c) 2000 Yggdrasil Computing, Inc.
 *
 * This driver is based on the 'USB Mass Storage Class' document. This
 * describes in detail the protocol used to communicate with such
 * devices.  Clearly, the designers had SCSI and ATAPI commands in
 * mind when they created this document.  The commands are all very
 * similar to commands in the SCSI-II and ATAPI specifications.
 *
 * It is important to note that in a number of cases this class
 * exhibits class-specific exemptions from the USB specification.
 * Notably the usage of NAK, STALL and ACK differs from the norm, in
 * that they are used to communicate wait, failed and OK on commands.
 *
 * Also, for certain devices, the interrupt endpoint is used to convey
 * status of a command.
 *
 * Please see http://www.one-eyed-alien.net/~mdharm/linux-usb for more
 * information about this driver.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <linux/sched.h>
#include <linux/errno.h>
#include <linux/freezer.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/kthread.h>
#include <linux/mutex.h>
#include <linux/utsname.h>

#include <scsi/scsi.h>
#include <scsi/scsi_cmnd.h>
#include <scsi/scsi_device.h>

#include "usb.h"
#include "scsiglue.h"
#include "transport.h"
#include "protocol.h"
#include "debug.h"
#include "initializers.h"

#include "sierra_ms.h"
#include "option_ms.h"

#include "msg/kcmsmonitormsgtypes.h"

#include "atpconfig.h"

/* Some informational data */
MODULE_AUTHOR("Matthew Dharm <mdharm-usb@one-eyed-alien.net>");
MODULE_DESCRIPTION("USB Mass Storage driver for Linux");
MODULE_LICENSE("GPL");

static unsigned int delay_use = 5;
module_param(delay_use, uint, S_IRUGO | S_IWUSR);
MODULE_PARM_DESC(delay_use, "seconds to delay before using a new device");

static char quirks[128];
module_param_string(quirks, quirks, sizeof(quirks), S_IRUGO | S_IWUSR);
MODULE_PARM_DESC(quirks, "supplemental list of device IDs and their quirks");


/*
 * The entries in this table correspond, line for line,
 * with the entries in usb_storage_usb_ids[], defined in usual-tables.c.
 */

/* The vendor name should be kept at eight characters or less, and
 * the product name should be kept at 16 characters or less. If a device
 * has the US_FL_FIX_INQUIRY flag, then the vendor and product names
 * normally generated by a device thorugh the INQUIRY response will be
 * taken from this list, and this is the reason for the above size
 * restriction. However, if the flag is not present, then you
 * are free to use as many characters as you like.
 */

#define UNUSUAL_DEV(idVendor, idProduct, bcdDeviceMin, bcdDeviceMax, \
		    vendor_name, product_name, use_protocol, use_transport, \
		    init_function, Flags) \
{ \
	.vendorName = vendor_name,	\
	.productName = product_name,	\
	.useProtocol = use_protocol,	\
	.useTransport = use_transport,	\
	.initFunction = init_function,	\
}

#define COMPLIANT_DEV	UNUSUAL_DEV

#define USUAL_DEV(use_protocol, use_transport, use_type) \
{ \
	.useProtocol = use_protocol,	\
	.useTransport = use_transport,	\
}

#ifdef CONFIG_ATP_USB_ADAPTOR
//!added by w00190448@20130425 start
#define HW_UNUSUAL_DEV(idVendor, cl, sc, pr, \
			vendor_name, product_name, use_protocol, use_transport, \
			init_function, Flags) \
			{ \
        		.vendorName = vendor_name,	\
        		.productName = product_name,	\
        		.useProtocol = use_protocol,	\
        		.useTransport = use_transport,	\
        		.initFunction = init_function,	\
			}
//!added by w00190448@20130425 end

#endif
static struct us_unusual_dev us_unusual_dev_list[] = {
#	include "unusual_devs.h" 
	{ }		/* Terminating entry */
};

#undef UNUSUAL_DEV
#undef COMPLIANT_DEV
#undef USUAL_DEV
#undef HW_UNUSUAL_DEV
#ifdef CONFIG_ATP_USB_ADAPTOR

/*Start of modified by lvxin 00135113 for support hspa 2009年4月29日*/
//extern int g_iDataCardIn;
extern atomic_t g_iDataCardIn;
extern int g_ulNumOfDataCard;
extern int isHWDataCardByUDev(struct usb_device  *);
extern int isZTEDataCardByUDev(struct usb_device  *);
/*End of modified by lvxin 00135113 for support hspa 2009年4月29日*/

//j00202470 for zte mf serial support

#define SMF_CMP_V_P                                       0x0001       /*匹配VID,PID后即进行切换标志*/
#define SMF_CMP_PT                                         0x0002      /*需匹配Product后才进行切换标志*/
#define SMF_CMP_MFR                                     0x0004      /*需匹配制作厂家后才进行切换标志*/
#define SMF_CMP_SN                                         0x0008      /*需匹配SN后才进行切换标志*/
#define MAX_NUM_PORTS		8	/* The maximum number of ports one device can grab at once */

/*Product ID, Manufacturer, Serial number*/
#define ZTE_VENDOR_ID	0xd219
#define ZTE_VENDOR_LITTLE_ENDIAN_ID	0x19d2

#define ZTE_PRODUCT_MF      "ZTE WCDMA Technologies MSM"
#define ZTE_MFR_MF          "ZTE,Incorporated"
#define ZTE_SN_MF           "673A3GLOD010000"
#define ZTE_PRODUCT_XS      "HSPA Data Card"
#define ZTE_MFR_XS          "USBModem"
#define ZTE_SN_XS           "1234567890ABCDEF"
#define ZTE_MF112_VID       0x19D2
#define ZTE_MF112_PID       0x2000
#define ZTE_XS_VID          0x1BBB
#define ZTE_XS_PID          0xF000

#define ZTE_MF680_VID  0xd219
#define ZTE_MF680_PID  0x5001 
#define ZTE_SN_MF680        "MF6800TMED010000"

#define ZTE_MF110_VID  0xd219
#define ZTE_MF110_PID  0x8300 
#define ZTE_SN_MF110        "P671A2TMED010000"


#define ZTE_SN_MF193    "P671A2TMED000000"
#define ZTE_SN_MF190    "P671A2TMED000000"

#define ZTE_SN_MF190_WOW "P671A2UCCS010000"


#define ZTE_MF193_CDROM_VID          0xd219
#define ZTE_MF193_CDROM_PID          0x4901

#define ZTE_MF190_CDROM_VID          0xd219
#define ZTE_MF190_CDROM_PID          0x0020

#define ZTE_MF193_MMC_VID          0xd219
#define ZTE_MF193_MMC_PID          0x2401

#define ZTE_MF626_VID  0xd219
#define ZTE_MF626_PID  0x3100 

//K5006-Z
#define ZTE_K5006_Z_VIP 0xd219
#define ZTE_K5006_Z_PID 0x1710

//MF668:    PID 0x0124, VID 0x19d2
#define ZTE_MF668_VID  0xd219
#define ZTE_MF668_PID  0x2401 

/*Message content for usb modem switch*/
#define ZTE_SWITCH_STR_MF   "55534243123456782000000080000c85010101180101010101000000000000"
#define ZTE_SWITCH_STR_XS   "55534243123456788000000080000606f50402527000000000000000000000"
#define ZTE_K5006_Z_SWITCH_STR "5553424312345678000000000000061b000000020000000000000000000000"

#define ZTE_CMD_01          "55534243000000002400000080000612000000240000000000000000000000"
#define ZTE_CMD_02          "55534243010000000000000000000600000000000000000000000000000000"     
#define ZTE_CMD_03          "55534243030000001200000080000c03000000120000000000000000000000"    
#define ZTE_CMD_04          "5553424302000000000000000000061b000000020000000000000000000000"         17.1.16       
//	

typedef struct _usb_modeswith_t
{
       char *ps_product;           /*产品型号*/
	char *ps_mfr;                  /*生产厂商*/
       char *ps_sn;                     /*序列号*/
    __u16 u16_id_vendor;        /*VID*/
    __u16 u16_id_product;      /*PID*/
    __u16 u16_flags;               /*匹配切换标志，值:SMF_CMP_V_P,SMF_CMP_PT,SMF_CMP_MFR,SMF_CMP_SN*/
    char *ps_hex_str;              /*切换指令*/              

    int ( *check_mode )( struct usb_device *dev );  /*检查USB的设备类型，判断是否:USB_CLASS_MASS_STORAGE*/
    int ( *mode_switch )( struct usb_interface *interface, char *ps_hex_str );  /*切换函数*/
    int ( *switch_complete )( void );/*切换完成函数*/
} usb_modeswith_t;

int usb_mode_switch( struct usb_interface *interface );
int usb_generic_check_mode( struct usb_device *dev );
int usb_generic_switch_mode( struct usb_interface *interface, char *ps_hex_str );

#if 1
/*数据卡信息，需进行匹配的内容和切换函数可以在此定义*/
static usb_modeswith_t g_device_switch[] = {

    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF, ZTE_K5006_Z_VIP, ZTE_K5006_Z_PID, SMF_CMP_V_P, 
        ZTE_K5006_Z_SWITCH_STR, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF, ZTE_MF112_VID, ZTE_MF112_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_XS, ZTE_MFR_XS, ZTE_SN_XS, ZTE_XS_VID, ZTE_XS_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_XS, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF193, ZTE_MF193_CDROM_VID, ZTE_MF193_CDROM_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_XS, ZTE_MFR_XS, ZTE_SN_MF193, ZTE_MF193_CDROM_VID, ZTE_MF193_CDROM_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_XS, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF193, ZTE_MF193_MMC_VID, ZTE_MF193_MMC_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_XS, ZTE_MFR_XS, ZTE_SN_MF193, ZTE_MF193_MMC_VID, ZTE_MF193_MMC_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_XS, usb_generic_check_mode, usb_generic_switch_mode, NULL},
        
    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF190_WOW, ZTE_MF190_CDROM_VID, ZTE_MF190_CDROM_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},

    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF193, ZTE_MF626_VID, ZTE_MF626_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},

    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF680, ZTE_MF680_VID, ZTE_MF680_PID, SMF_CMP_V_P, 
        ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},

    {ZTE_PRODUCT_MF, ZTE_MFR_MF, ZTE_SN_MF110, ZTE_MF110_VID, ZTE_MF110_PID, SMF_CMP_V_P, 
            ZTE_SWITCH_STR_MF, usb_generic_check_mode, usb_generic_switch_mode, NULL},

    {}
};
#endif

/*Start of modified by lvxin 00135113 to prohibit datacard and usb printer send signal to usbmount 2009年8月31日*/
#if defined (CONFIG_USB_STORAGE) || defined (CONFIG_USB_STORAGE_MODULE)
#define ATP_SUPPORT_REPORT_USER 1
#endif
#ifdef ATP_SUPPORT_REPORT_USER
static struct task_struct *user_app = NULL; 
extern char pid_str[];
#endif
/*End of modified by lvxin 00135113 to prohibit datacard and usb printer send signal to usbmount 2009年8月31日*/
#endif
#ifdef CONFIG_PM	/* Minimal support for suspend and resume */

int usb_stor_suspend(struct usb_interface *iface, pm_message_t message)
{
	struct us_data *us = usb_get_intfdata(iface);

	/* Wait until no command is running */
	mutex_lock(&us->dev_mutex);

	US_DEBUGP("%s\n", __func__);
	if (us->suspend_resume_hook)
		(us->suspend_resume_hook)(us, US_SUSPEND);

	/* When runtime PM is working, we'll set a flag to indicate
	 * whether we should autoresume when a SCSI request arrives. */

	mutex_unlock(&us->dev_mutex);
	return 0;
}
EXPORT_SYMBOL_GPL(usb_stor_suspend);

int usb_stor_resume(struct usb_interface *iface)
{
	struct us_data *us = usb_get_intfdata(iface);

	mutex_lock(&us->dev_mutex);

	US_DEBUGP("%s\n", __func__);
	if (us->suspend_resume_hook)
		(us->suspend_resume_hook)(us, US_RESUME);

	mutex_unlock(&us->dev_mutex);
	return 0;
}
EXPORT_SYMBOL_GPL(usb_stor_resume);

int usb_stor_reset_resume(struct usb_interface *iface)
{
	struct us_data *us = usb_get_intfdata(iface);

	US_DEBUGP("%s\n", __func__);

	/* Report the reset to the SCSI core */
	usb_stor_report_bus_reset(us);

	/* FIXME: Notify the subdrivers that they need to reinitialize
	 * the device */
	return 0;
}
EXPORT_SYMBOL_GPL(usb_stor_reset_resume);

#endif /* CONFIG_PM */

/*
 * The next two routines get called just before and just after
 * a USB port reset, whether from this driver or a different one.
 */

int usb_stor_pre_reset(struct usb_interface *iface)
{
	struct us_data *us = usb_get_intfdata(iface);

	US_DEBUGP("%s\n", __func__);

	/* Make sure no command runs during the reset */
	mutex_lock(&us->dev_mutex);
	return 0;
}
EXPORT_SYMBOL_GPL(usb_stor_pre_reset);

int usb_stor_post_reset(struct usb_interface *iface)
{
	struct us_data *us = usb_get_intfdata(iface);

	US_DEBUGP("%s\n", __func__);

	/* Report the reset to the SCSI core */
	usb_stor_report_bus_reset(us);

	/* FIXME: Notify the subdrivers that they need to reinitialize
	 * the device */

	mutex_unlock(&us->dev_mutex);
	return 0;
}
EXPORT_SYMBOL_GPL(usb_stor_post_reset);

/*
 * fill_inquiry_response takes an unsigned char array (which must
 * be at least 36 characters) and populates the vendor name,
 * product name, and revision fields. Then the array is copied
 * into the SCSI command's response buffer (oddly enough
 * called request_buffer). data_len contains the length of the
 * data array, which again must be at least 36.
 */

void fill_inquiry_response(struct us_data *us, unsigned char *data,
		unsigned int data_len)
{
	if (data_len<36) // You lose.
		return;

	if(data[0]&0x20) { /* USB device currently not connected. Return
			      peripheral qualifier 001b ("...however, the
			      physical device is not currently connected
			      to this logical unit") and leave vendor and
			      product identification empty. ("If the target
			      does store some of the INQUIRY data on the
			      device, it may return zeros or ASCII spaces 
			      (20h) in those fields until the data is
			      available from the device."). */
		memset(data+8,0,28);
	} else {
		u16 bcdDevice = le16_to_cpu(us->pusb_dev->descriptor.bcdDevice);
		memcpy(data+8, us->unusual_dev->vendorName, 
			strlen(us->unusual_dev->vendorName) > 8 ? 8 :
			strlen(us->unusual_dev->vendorName));
		memcpy(data+16, us->unusual_dev->productName, 
			strlen(us->unusual_dev->productName) > 16 ? 16 :
			strlen(us->unusual_dev->productName));
		data[32] = 0x30 + ((bcdDevice>>12) & 0x0F);
		data[33] = 0x30 + ((bcdDevice>>8) & 0x0F);
		data[34] = 0x30 + ((bcdDevice>>4) & 0x0F);
		data[35] = 0x30 + ((bcdDevice) & 0x0F);
	}

	usb_stor_set_xfer_buf(data, data_len, us->srb);
}
EXPORT_SYMBOL_GPL(fill_inquiry_response);



#ifdef CONFIG_ATP_USB_ADAPTOR
/*Start of modified by lvxin 00135113 for support hspa 2009年8月19日*/
int sendHWCardCmd(struct Scsi_Host *host)
{
    struct us_data* us = host_to_us(host);

    /*增加数据卡PC切换模式start*/
    //if (g_iDataCardIn == 3)
    if (atomic_read(&g_iDataCardIn) == 3)
    {
        printk("\n===start to send Set_feature_D command==\n");
        atomic_set(&g_iDataCardIn, 4);
#if 1
        us->iobuf[0] = 0x1;

        usb_stor_control_msg(us, us->send_ctrl_pipe,
        USB_REQ_SET_FEATURE, USB_TYPE_STANDARD | USB_RECIP_DEVICE, 
        0x01, 0x0, us->iobuf, 0x1, 1000);
#endif
        //g_iDataCardIn = 4;  
     }   
    return 0;
}
EXPORT_SYMBOL(sendHWCardCmd);
/*End of modified by lvxin 00135113 for support hspa 2009年8月19日*/
#endif
static int usb_stor_control_thread(void * __us)
{
	struct us_data *us = (struct us_data *)__us;
	struct Scsi_Host *host = us_to_host(us);

	for(;;) {
		US_DEBUGP("*** thread sleeping.\n");
		if (wait_for_completion_interruptible(&us->cmnd_ready))
			break;

		US_DEBUGP("*** thread awakened.\n");

		/* lock the device pointers */
		mutex_lock(&(us->dev_mutex));

		/* lock access to the state */
		scsi_lock(host);

		/* When we are called with no command pending, we're done */
		if (us->srb == NULL) {
			scsi_unlock(host);
			mutex_unlock(&us->dev_mutex);
			US_DEBUGP("-- exiting\n");
			break;
		}

		/* has the command timed out *already* ? */
		if (test_bit(US_FLIDX_TIMED_OUT, &us->dflags)) {
			us->srb->result = DID_ABORT << 16;
			goto SkipForAbort;
		}

		scsi_unlock(host);

		/* reject the command if the direction indicator 
		 * is UNKNOWN
		 */
		if (us->srb->sc_data_direction == DMA_BIDIRECTIONAL) {
			US_DEBUGP("UNKNOWN data direction\n");
			us->srb->result = DID_ERROR << 16;
		}

		/* reject if target != 0 or if LUN is higher than
		 * the maximum known LUN
		 */
		else if (us->srb->device->id && 
				!(us->fflags & US_FL_SCM_MULT_TARG)) {
			US_DEBUGP("Bad target number (%d:%d)\n",
				  us->srb->device->id, us->srb->device->lun);
			us->srb->result = DID_BAD_TARGET << 16;
		}

		else if (us->srb->device->lun > us->max_lun) {
			US_DEBUGP("Bad LUN (%d:%d)\n",
				  us->srb->device->id, us->srb->device->lun);
			us->srb->result = DID_BAD_TARGET << 16;
		}

		/* Handle those devices which need us to fake 
		 * their inquiry data */
		else if ((us->srb->cmnd[0] == INQUIRY) &&
			    (us->fflags & US_FL_FIX_INQUIRY)) {
			unsigned char data_ptr[36] = {
			    0x00, 0x80, 0x02, 0x02,
			    0x1F, 0x00, 0x00, 0x00};

			US_DEBUGP("Faking INQUIRY command\n");
			fill_inquiry_response(us, data_ptr, 36);
			us->srb->result = SAM_STAT_GOOD;
		}

		/* we've got a command, let's do it! */
		else {
			US_DEBUG(usb_stor_show_command(us->srb));
			us->proto_handler(us->srb, us);
		}

		/* lock access to the state */
		scsi_lock(host);

		/* indicate that the command is done */
		if (us->srb->result != DID_ABORT << 16) {
			US_DEBUGP("scsi cmd done, result=0x%x\n", 
				   us->srb->result);
			us->srb->scsi_done(us->srb);
		} else {
SkipForAbort:
			US_DEBUGP("scsi command aborted\n");
		}

		/* If an abort request was received we need to signal that
		 * the abort has finished.  The proper test for this is
		 * the TIMED_OUT flag, not srb->result == DID_ABORT, because
		 * the timeout might have occurred after the command had
		 * already completed with a different result code. */
		if (test_bit(US_FLIDX_TIMED_OUT, &us->dflags)) {
			complete(&(us->notify));

			/* Allow USB transfers to resume */
			clear_bit(US_FLIDX_ABORTING, &us->dflags);
			clear_bit(US_FLIDX_TIMED_OUT, &us->dflags);
		}

		/* finished working on this command */
		us->srb = NULL;
		scsi_unlock(host);

		/* unlock the device pointers */
		mutex_unlock(&us->dev_mutex);
	} /* for (;;) */

	/* Wait until we are told to stop */
	for (;;) {
		set_current_state(TASK_INTERRUPTIBLE);
		if (kthread_should_stop())
			break;
		schedule();
	}
	__set_current_state(TASK_RUNNING);
	return 0;
}	

/***********************************************************************
 * Device probing and disconnecting
 ***********************************************************************/

/* Associate our private data with the USB device */
static int associate_dev(struct us_data *us, struct usb_interface *intf)
{
	US_DEBUGP("-- %s\n", __func__);

	/* Fill in the device-related fields */
	us->pusb_dev = interface_to_usbdev(intf);
	us->pusb_intf = intf;
	us->ifnum = intf->cur_altsetting->desc.bInterfaceNumber;
	US_DEBUGP("Vendor: 0x%04x, Product: 0x%04x, Revision: 0x%04x\n",
			le16_to_cpu(us->pusb_dev->descriptor.idVendor),
			le16_to_cpu(us->pusb_dev->descriptor.idProduct),
			le16_to_cpu(us->pusb_dev->descriptor.bcdDevice));
	US_DEBUGP("Interface Subclass: 0x%02x, Protocol: 0x%02x\n",
			intf->cur_altsetting->desc.bInterfaceSubClass,
			intf->cur_altsetting->desc.bInterfaceProtocol);

	/* Store our private data in the interface */
	usb_set_intfdata(intf, us);

#if defined(CONFIG_USB_HSAN_USB3_0)
	/* Allocate the control/setup and DMA-mapped buffers */
	us->cr = kmalloc(sizeof(*us->cr), GFP_KERNEL);
#else
	/* Allocate the device-related DMA-mapped buffers */
	us->cr = usb_buffer_alloc(us->pusb_dev, sizeof(*us->cr),
			GFP_KERNEL, &us->cr_dma);
#endif	
	
	if (!us->cr) {
		US_DEBUGP("usb_ctrlrequest allocation failed\n");
		return -ENOMEM;
	}
#if defined(CONFIG_USB_HSAN_USB3_0)
	us->iobuf = usb_alloc_coherent(us->pusb_dev, US_IOBUF_SIZE,
			GFP_KERNEL, &us->iobuf_dma);
#else
	us->iobuf = usb_buffer_alloc(us->pusb_dev, US_IOBUF_SIZE,
			GFP_KERNEL, &us->iobuf_dma);
#endif			
	if (!us->iobuf) {
		US_DEBUGP("I/O buffer allocation failed\n");
		return -ENOMEM;
	}
	return 0;
}

/* Works only for digits and letters, but small and fast */
#define TOLOWER(x) ((x) | 0x20)

/* Adjust device flags based on the "quirks=" module parameter */
static void adjust_quirks(struct us_data *us)
{
	char *p;
	u16 vid = le16_to_cpu(us->pusb_dev->descriptor.idVendor);
	u16 pid = le16_to_cpu(us->pusb_dev->descriptor.idProduct);
	unsigned f = 0;
	unsigned int mask = (US_FL_SANE_SENSE | US_FL_FIX_CAPACITY |
			US_FL_CAPACITY_HEURISTICS | US_FL_IGNORE_DEVICE |
			US_FL_NOT_LOCKABLE | US_FL_MAX_SECTORS_64 |
			US_FL_CAPACITY_OK | US_FL_IGNORE_RESIDUE |
			US_FL_SINGLE_LUN | US_FL_NO_WP_DETECT);

	p = quirks;
	while (*p) {
		/* Each entry consists of VID:PID:flags */
		if (vid == simple_strtoul(p, &p, 16) &&
				*p == ':' &&
				pid == simple_strtoul(p+1, &p, 16) &&
				*p == ':')
			break;

		/* Move forward to the next entry */
		while (*p) {
			if (*p++ == ',')
				break;
		}
	}
	if (!*p)	/* No match */
		return;

	/* Collect the flags */
	while (*++p && *p != ',') {
		switch (TOLOWER(*p)) {
		case 'a':
			f |= US_FL_SANE_SENSE;
			break;
		case 'c':
			f |= US_FL_FIX_CAPACITY;
			break;
		case 'h':
			f |= US_FL_CAPACITY_HEURISTICS;
			break;
		case 'i':
			f |= US_FL_IGNORE_DEVICE;
			break;
		case 'l':
			f |= US_FL_NOT_LOCKABLE;
			break;
		case 'm':
			f |= US_FL_MAX_SECTORS_64;
			break;
		case 'o':
			f |= US_FL_CAPACITY_OK;
			break;
		case 'r':
			f |= US_FL_IGNORE_RESIDUE;
			break;
		case 's':
			f |= US_FL_SINGLE_LUN;
			break;
		case 'w':
			f |= US_FL_NO_WP_DETECT;
			break;
		/* Ignore unrecognized flag characters */
		}
	}
	us->fflags = (us->fflags & ~mask) | f;
	dev_info(&us->pusb_intf->dev, "Quirks match for "
			"vid %04x pid %04x: %x\n",
			vid, pid, f);
}

/* Get the unusual_devs entries and the string descriptors */
static int get_device_info(struct us_data *us, const struct usb_device_id *id,
		struct us_unusual_dev *unusual_dev)
{
	struct usb_device *dev = us->pusb_dev;
	struct usb_interface_descriptor *idesc =
		&us->pusb_intf->cur_altsetting->desc;

	/* Store the entries */
	us->unusual_dev = unusual_dev;
	us->subclass = (unusual_dev->useProtocol == US_SC_DEVICE) ?
			idesc->bInterfaceSubClass :
			unusual_dev->useProtocol;
	us->protocol = (unusual_dev->useTransport == US_PR_DEVICE) ?
			idesc->bInterfaceProtocol :
			unusual_dev->useTransport;
	us->fflags = USB_US_ORIG_FLAGS(id->driver_info);
	adjust_quirks(us);

	if (us->fflags & US_FL_IGNORE_DEVICE) {
		printk(KERN_INFO USB_STORAGE "device ignored\n");
		return -ENODEV;
	}

	/*
	 * This flag is only needed when we're in high-speed, so let's
	 * disable it if we're in full-speed
	 */
	if (dev->speed != USB_SPEED_HIGH)
		us->fflags &= ~US_FL_GO_SLOW;

	/* Log a message if a non-generic unusual_dev entry contains an
	 * unnecessary subclass or protocol override.  This may stimulate
	 * reports from users that will help us remove unneeded entries
	 * from the unusual_devs.h table.
	 */
	if (id->idVendor || id->idProduct) {
		static const char *msgs[3] = {
			"an unneeded SubClass entry",
			"an unneeded Protocol entry",
			"unneeded SubClass and Protocol entries"};
		struct usb_device_descriptor *ddesc = &dev->descriptor;
		int msg = -1;

		if (unusual_dev->useProtocol != US_SC_DEVICE &&
			us->subclass == idesc->bInterfaceSubClass)
			msg += 1;
		if (unusual_dev->useTransport != US_PR_DEVICE &&
			us->protocol == idesc->bInterfaceProtocol)
			msg += 2;
		if (msg >= 0 && !(us->fflags & US_FL_NEED_OVERRIDE))
			printk(KERN_NOTICE USB_STORAGE "This device "
				"(%04x,%04x,%04x S %02x P %02x)"
				" has %s in unusual_devs.h (kernel"
				" %s)\n"
				"   Please send a copy of this message to "
				"<linux-usb@vger.kernel.org> and "
				"<usb-storage@lists.one-eyed-alien.net>\n",
				le16_to_cpu(ddesc->idVendor),
				le16_to_cpu(ddesc->idProduct),
				le16_to_cpu(ddesc->bcdDevice),
				idesc->bInterfaceSubClass,
				idesc->bInterfaceProtocol,
				msgs[msg],
				utsname()->release);
	}

	return 0;
}

/* Get the transport settings */
static void get_transport(struct us_data *us)
{
	switch (us->protocol) {
	case US_PR_CB:
		us->transport_name = "Control/Bulk";
		us->transport = usb_stor_CB_transport;
		us->transport_reset = usb_stor_CB_reset;
		us->max_lun = 7;
		break;

	case US_PR_CBI:
		us->transport_name = "Control/Bulk/Interrupt";
		us->transport = usb_stor_CB_transport;
		us->transport_reset = usb_stor_CB_reset;
		us->max_lun = 7;
		break;

	case US_PR_BULK:
		us->transport_name = "Bulk";
		us->transport = usb_stor_Bulk_transport;
		us->transport_reset = usb_stor_Bulk_reset;
		break;
	}
}

/* Get the protocol settings */
static void get_protocol(struct us_data *us)
{
	switch (us->subclass) {
	case US_SC_RBC:
		us->protocol_name = "Reduced Block Commands (RBC)";
		us->proto_handler = usb_stor_transparent_scsi_command;
		break;

	case US_SC_8020:
		us->protocol_name = "8020i";
		us->proto_handler = usb_stor_pad12_command;
		us->max_lun = 0;
		break;

	case US_SC_QIC:
		us->protocol_name = "QIC-157";
		us->proto_handler = usb_stor_pad12_command;
		us->max_lun = 0;
		break;

	case US_SC_8070:
		us->protocol_name = "8070i";
		us->proto_handler = usb_stor_pad12_command;
		us->max_lun = 0;
		break;

	case US_SC_SCSI:
		us->protocol_name = "Transparent SCSI";
		us->proto_handler = usb_stor_transparent_scsi_command;
		break;

	case US_SC_UFI:
		us->protocol_name = "Uniform Floppy Interface (UFI)";
		us->proto_handler = usb_stor_ufi_command;
		break;
	}
}

/* Get the pipe settings */
static int get_pipes(struct us_data *us)
{
	struct usb_host_interface *altsetting =
		us->pusb_intf->cur_altsetting;
	int i;
	struct usb_endpoint_descriptor *ep;
	struct usb_endpoint_descriptor *ep_in = NULL;
	struct usb_endpoint_descriptor *ep_out = NULL;
	struct usb_endpoint_descriptor *ep_int = NULL;

	/*
	 * Find the first endpoint of each type we need.
	 * We are expecting a minimum of 2 endpoints - in and out (bulk).
	 * An optional interrupt-in is OK (necessary for CBI protocol).
	 * We will ignore any others.
	 */
	for (i = 0; i < altsetting->desc.bNumEndpoints; i++) {
		ep = &altsetting->endpoint[i].desc;

		if (usb_endpoint_xfer_bulk(ep)) {
			if (usb_endpoint_dir_in(ep)) {
				if (!ep_in)
					ep_in = ep;
			} else {
				if (!ep_out)
					ep_out = ep;
			}
		}

		else if (usb_endpoint_is_int_in(ep)) {
			if (!ep_int)
				ep_int = ep;
		}
	}

	if (!ep_in || !ep_out || (us->protocol == US_PR_CBI && !ep_int)) {
		US_DEBUGP("Endpoint sanity check failed! Rejecting dev.\n");
		return -EIO;
	}

	/* Calculate and store the pipe values */
	us->send_ctrl_pipe = usb_sndctrlpipe(us->pusb_dev, 0);
	us->recv_ctrl_pipe = usb_rcvctrlpipe(us->pusb_dev, 0);
	us->send_bulk_pipe = usb_sndbulkpipe(us->pusb_dev,
		usb_endpoint_num(ep_out));
	us->recv_bulk_pipe = usb_rcvbulkpipe(us->pusb_dev, 
		usb_endpoint_num(ep_in));
	if (ep_int) {
		us->recv_intr_pipe = usb_rcvintpipe(us->pusb_dev,
			usb_endpoint_num(ep_int));
		us->ep_bInterval = ep_int->bInterval;
	}
	return 0;
}

/* Initialize all the dynamic resources we need */
static int usb_stor_acquire_resources(struct us_data *us)
{
	int p;
	struct task_struct *th;

	us->current_urb = usb_alloc_urb(0, GFP_KERNEL);
	if (!us->current_urb) {
		US_DEBUGP("URB allocation failed\n");
		return -ENOMEM;
	}

	/* Just before we start our control thread, initialize
	 * the device if it needs initialization */
	if (us->unusual_dev->initFunction) {
		p = us->unusual_dev->initFunction(us);
		if (p)
			return p;
	}

	/* Start up our control thread */
	th = kthread_run(usb_stor_control_thread, us, "usb-storage");
	if (IS_ERR(th)) {
		printk(KERN_WARNING USB_STORAGE 
		       "Unable to start control thread\n");
		return PTR_ERR(th);
	}
	us->ctl_thread = th;

	return 0;
}

/* Release all our dynamic resources */
static void usb_stor_release_resources(struct us_data *us)
{
	US_DEBUGP("-- %s\n", __func__);

	/* Tell the control thread to exit.  The SCSI host must
	 * already have been removed and the DISCONNECTING flag set
	 * so that we won't accept any more commands.
	 */
	US_DEBUGP("-- sending exit command to thread\n");
	complete(&us->cmnd_ready);
	if (us->ctl_thread)
		kthread_stop(us->ctl_thread);

	/* Call the destructor routine, if it exists */
	if (us->extra_destructor) {
		US_DEBUGP("-- calling extra_destructor()\n");
		us->extra_destructor(us->extra);
	}

	/* Free the extra data and the URB */
	kfree(us->extra);
	usb_free_urb(us->current_urb);
}

/* Dissociate from the USB device */
static void dissociate_dev(struct us_data *us)
{
	US_DEBUGP("-- %s\n", __func__);
#if defined(CONFIG_USB_HSAN_USB3_0)
	/* Free the buffers */
	kfree(us->cr);
	usb_free_coherent(us->pusb_dev, US_IOBUF_SIZE, us->iobuf, us->iobuf_dma);
#else
		/* Free the device-related DMA-mapped buffers */
	if (us->cr)
		usb_buffer_free(us->pusb_dev, sizeof(*us->cr), us->cr,
				us->cr_dma);
	if (us->iobuf)
		usb_buffer_free(us->pusb_dev, US_IOBUF_SIZE, us->iobuf,
				us->iobuf_dma);
#endif	

	/* Remove our private data from the interface */
	usb_set_intfdata(us->pusb_intf, NULL);
}

/* First stage of disconnect processing: stop SCSI scanning,
 * remove the host, and stop accepting new commands
 */
static void quiesce_and_remove_host(struct us_data *us)
{
	struct Scsi_Host *host = us_to_host(us);

	/* If the device is really gone, cut short reset delays */
	if (us->pusb_dev->state == USB_STATE_NOTATTACHED)
		set_bit(US_FLIDX_DISCONNECTING, &us->dflags);

	/* Prevent SCSI-scanning (if it hasn't started yet)
	 * and wait for the SCSI-scanning thread to stop.
	 */
	set_bit(US_FLIDX_DONT_SCAN, &us->dflags);
	wake_up(&us->delay_wait);
	wait_for_completion(&us->scanning_done);

	/* Removing the host will perform an orderly shutdown: caches
	 * synchronized, disks spun down, etc.
	 */
	scsi_remove_host(host);

	/* Prevent any new commands from being accepted and cut short
	 * reset delays.
	 */
	scsi_lock(host);
	set_bit(US_FLIDX_DISCONNECTING, &us->dflags);
	scsi_unlock(host);
	wake_up(&us->delay_wait);
}

/* Second stage of disconnect processing: deallocate all resources */
static void release_everything(struct us_data *us)
{
	usb_stor_release_resources(us);
	dissociate_dev(us);

	/* Drop our reference to the host; the SCSI core will free it
	 * (and "us" along with it) when the refcount becomes 0. */
	scsi_host_put(us_to_host(us));
}

#ifdef CONFIG_ATP_USB_ADAPTOR
#ifdef SUPPORT_ATP_WANUMTS

#include <linux/proc_fs.h>

//!判断数据卡芯片平台，方便切换到对应SCSI命令by 00190448@20130419 start
#define BALONGDATACARD 0x0201
#define BALONGDATACARD_BIGEND 0x0102

int g_iBalongDataCard = 1;//0:代表高通数据卡，1:代表balong数据卡
EXPORT_SYMBOL(g_iBalongDataCard);

extern struct proc_dir_entry proc_root;

static int proc_user_datacardchip_wr (struct file *file,
                             const char *buffer,
                             unsigned long count,
                             void *data)
{
   sscanf( buffer,"%d",&g_iBalongDataCard);
   return count;
}
int proc_user_datacardchip_rd(char *buf, char **start, off_t offset,
                   int count, int *eof, void *data)
{
    int len = 0;
    len += sprintf (buf + len, "%d",g_iBalongDataCard);
    return len;
}
static void proc_user_datacardchip_create(void)
{
    struct proc_dir_entry* proc_umts = NULL;
    proc_umts = create_proc_entry("proc_user_datacardchip", S_IFREG | S_IRWXU , &proc_root ); 
    proc_umts->write_proc = (write_proc_t *)proc_user_datacardchip_wr;
    proc_umts->read_proc = (read_proc_t *)proc_user_datacardchip_rd;
}
static void proc_user_datacardchip_remove(void)
{
	remove_proc_entry("proc_user_datacardchip", NULL /* parent dir */);
}
#endif
#endif

/* Thread to carry out delayed SCSI-device scanning */
static int usb_stor_scan_thread(void * __us)
{
	struct us_data *us = (struct us_data *)__us;

	printk(KERN_DEBUG
		"usb-storage: device found at %d\n", us->pusb_dev->devnum);

	set_freezable();

#ifdef CONFIG_ATP_USB_ADAPTOR
#ifdef SUPPORT_ATP_WANUMTS
//!判断数据卡芯片平台，方便切换到对应SCSI命令by 00190448@20130419 start
        if((us->pusb_dev->descriptor.bcdDevice == BALONGDATACARD_BIGEND)||(us->pusb_dev->descriptor.bcdDevice == BALONGDATACARD))
        {
            printk("\nThis is Balong Platform\n");
            g_iBalongDataCard = 1;//为balong数据卡
        }
        else
        {
            g_iBalongDataCard = 0;//为非balong数据卡      
        }
//!判断数据卡芯片平台，方便切换到对应SCSI命令by 00190448@20130419 start
#endif
#endif

	/* Wait for the timeout to expire or for a disconnect */
	if (delay_use > 0) {
		printk(KERN_DEBUG "usb-storage: waiting for device "
				"to settle before scanning\n");
		wait_event_freezable_timeout(us->delay_wait,
				test_bit(US_FLIDX_DONT_SCAN, &us->dflags),
				delay_use * HZ);
	}
    
	/* If the device is still connected, perform the scanning */
	if (!test_bit(US_FLIDX_DONT_SCAN, &us->dflags)) {

		/* For bulk-only devices, determine the max LUN value */
		if (us->protocol == US_PR_BULK &&
				!(us->fflags & US_FL_SINGLE_LUN)) {
			mutex_lock(&us->dev_mutex);
			us->max_lun = usb_stor_Bulk_max_lun(us);
			mutex_unlock(&us->dev_mutex);
		}
		scsi_scan_host(us_to_host(us));
		printk(KERN_DEBUG "usb-storage: device scan complete\n");

		/* Should we unbind if no devices were detected? */
	}

	complete_and_exit(&us->scanning_done, 0);
}


/* First part of general USB mass-storage probing */
int usb_stor_probe1(struct us_data **pus,
		struct usb_interface *intf,
		const struct usb_device_id *id,
		struct us_unusual_dev *unusual_dev)
{
	struct Scsi_Host *host;
	struct us_data *us;
	int result;

	US_DEBUGP("USB Mass Storage device detected\n");

	/*
	 * Ask the SCSI layer to allocate a host structure, with extra
	 * space at the end for our private us_data structure.
	 */
	host = scsi_host_alloc(&usb_stor_host_template, sizeof(*us));
	if (!host) {
		printk(KERN_WARNING USB_STORAGE
			"Unable to allocate the scsi host\n");
		return -ENOMEM;
	}

	/*
	 * Allow 16-byte CDBs and thus > 2TB
	 */
	host->max_cmd_len = 16;
	*pus = us = host_to_us(host);
	memset(us, 0, sizeof(struct us_data));
	mutex_init(&(us->dev_mutex));
	init_completion(&us->cmnd_ready);
	init_completion(&(us->notify));
	init_waitqueue_head(&us->delay_wait);
	init_completion(&us->scanning_done);

#ifdef CONFIG_ATP_USB_ADAPTOR
	/*start of 添加ZTE数据卡的切换模式,从CD-Rom切换到modem模式 by z00166803 at 20100730*/
    if(!usb_mode_switch( intf ))
	{
	    printk("set g_iDataCardIn,4 \n");
     	    atomic_set(&g_iDataCardIn,4);
    }
    /*end of 添加ZTE数据卡的切换模式,从CD-Rom切换到modem模式 by z00166803 at 20100730*/
#endif   


	/* Associate the us_data structure with the USB device */
	result = associate_dev(us, intf);
	if (result)
		goto BadDevice;

	/* Get the unusual_devs entries and the descriptors */
	result = get_device_info(us, id, unusual_dev);
	if (result)
		goto BadDevice;

	/* Get standard transport and protocol settings */
	get_transport(us);
	get_protocol(us);

	/* Give the caller a chance to fill in specialized transport
	 * or protocol settings.
	 */
	return 0;

BadDevice:
	US_DEBUGP("storage_probe() failed\n");
	release_everything(us);
	return result;
}
EXPORT_SYMBOL_GPL(usb_stor_probe1);

/* Second part of general USB mass-storage probing */
int usb_stor_probe2(struct us_data *us)
{
	struct task_struct *th;
	int result;

	/* Make sure the transport and protocol have both been set */
	if (!us->transport || !us->proto_handler) {
		result = -ENXIO;
		goto BadDevice;
	}
	US_DEBUGP("Transport: %s\n", us->transport_name);
	US_DEBUGP("Protocol: %s\n", us->protocol_name);

	/* fix for single-lun devices */
	if (us->fflags & US_FL_SINGLE_LUN)
		us->max_lun = 0;

	/* Find the endpoints and calculate pipe values */
	result = get_pipes(us);
	if (result)
		goto BadDevice;

	/* Acquire all the other resources and add the host */
	result = usb_stor_acquire_resources(us);
	if (result)
		goto BadDevice;
	result = scsi_add_host(us_to_host(us), &us->pusb_intf->dev);
	if (result) {
		printk(KERN_WARNING USB_STORAGE
			"Unable to add the scsi host\n");
		goto BadDevice;
	}

	/* Start up the thread for delayed SCSI-device scanning */
	th = kthread_create(usb_stor_scan_thread, us, "usb-stor-scan");
	if (IS_ERR(th)) {
		printk(KERN_WARNING USB_STORAGE 
		       "Unable to start the device-scanning thread\n");
		complete(&us->scanning_done);
		quiesce_and_remove_host(us);
		result = PTR_ERR(th);
		goto BadDevice;
	}

	wake_up_process(th);

	return 0;

	/* We come here if there are any problems */
BadDevice:
	US_DEBUGP("storage_probe() failed\n");
	release_everything(us);
	return result;
}
EXPORT_SYMBOL_GPL(usb_stor_probe2);

/* Handle a USB mass-storage disconnect */
void usb_stor_disconnect(struct usb_interface *intf)
{
	struct us_data *us = usb_get_intfdata(intf);
#ifdef CONFIG_ATP_USB_ADAPTOR	
	struct usb_device *udev = interface_to_usbdev(intf);

	/*Start of modified by lvxin 00135113 to prohibit datacard and usb printer send signal to usbmount*/
	if(!isHWDataCardByUDev(udev))
	{
		//printk("\n==file:%s,line:%d,func:%s=this is usb device=\n",__FILE__,__LINE__,__FUNCTION__);
#ifdef ATP_SUPPORT_REPORT_USER
#if 0
		long pid = simple_strtol(pid_str, NULL, 10);         
		if ( pid != 0 )
		{
			printk("PID from USB module, %d\n", pid);
			user_app = find_task_by_vpid(pid);
			/* send SIGUSR1 */
			if(user_app)
			{
				send_sig(SIGUSR1, user_app, 0);
			}
		}
#endif
		syswatch_nl_send( ATP_MSG_MONITOR_EVT_USBSTORAGE_PLUGOUT, NULL, 0 );
#endif        
	}

	/*End of modified by lvxin 00135113 to prohibit datacard and usb printer send signal to usbmount*/
#endif	
	US_DEBUGP("storage_disconnect() called\n");
	quiesce_and_remove_host(us);
	release_everything(us);
}
EXPORT_SYMBOL_GPL(usb_stor_disconnect);

/* The main probe routine for standard devices */
static int storage_probe(struct usb_interface *intf,
			 const struct usb_device_id *id)
{
	struct us_data *us;
	int result;

	/*
	 * If libusual is configured, let it decide whether a standard
	 * device should be handled by usb-storage or by ub.
	 * If the device isn't standard (is handled by a subdriver
	 * module) then don't accept it.
	 */
	if (usb_usual_check_type(id, USB_US_TYPE_STOR) ||
			usb_usual_ignore_device(intf))
		return -ENXIO;

	/*
	 * Call the general probe procedures.
	 *
	 * The unusual_dev_list array is parallel to the usb_storage_usb_ids
	 * table, so we use the index of the id entry to find the
	 * corresponding unusual_devs entry.
	 */
	result = usb_stor_probe1(&us, intf, id,
			(id - usb_storage_usb_ids) + us_unusual_dev_list);
	if (result)
		return result;

	/* No special transport or protocol settings in the main module */

	result = usb_stor_probe2(us);
	return result;
}

/***********************************************************************
 * Initialization and registration
 ***********************************************************************/

static struct usb_driver usb_storage_driver = {
	.name =		"usb-storage",
	.probe =	storage_probe,
	.disconnect =	usb_stor_disconnect,
	.suspend =	usb_stor_suspend,
	.resume =	usb_stor_resume,
	.reset_resume =	usb_stor_reset_resume,
	.pre_reset =	usb_stor_pre_reset,
	.post_reset =	usb_stor_post_reset,
	.id_table =	usb_storage_usb_ids,
	.soft_unbind =	1,
};

static int __init usb_stor_init(void)
{
	int retval;

	printk(KERN_INFO "Initializing USB Mass Storage driver...\n");

	/* register the driver, return usb_register return code if error */
	retval = usb_register(&usb_storage_driver);
	if (retval == 0) {
		printk(KERN_INFO "USB Mass Storage support registered.\n");
		usb_usual_set_present(USB_US_TYPE_STOR);
	}

//!用来记录数据卡芯片类型:balong or qualcomm by w00190448 start
#ifdef CONFIG_ATP_USB_ADAPTOR
#ifdef SUPPORT_ATP_WANUMTS
    proc_user_datacardchip_create();
#endif
#endif
//!用来记录数据卡芯片类型:balong or qualcomm by w00190448 end

	return retval;
}

static void __exit usb_stor_exit(void)
{
	US_DEBUGP("usb_stor_exit() called\n");

	/* Deregister the driver
	 * This will cause disconnect() to be called for each
	 * attached unit
	 */
	US_DEBUGP("-- calling usb_deregister()\n");
	usb_deregister(&usb_storage_driver) ;

//!用来记录数据卡芯片类型:balong or qualcomm by w00190448 start
#ifdef CONFIG_ATP_USB_ADAPTOR
#ifdef SUPPORT_ATP_WANUMTS
       proc_user_datacardchip_remove();
#endif
#endif
//!用来记录数据卡芯片类型:balong or qualcomm by w00190448 end
   
	usb_usual_clear_present(USB_US_TYPE_STOR);
}

module_init(usb_stor_init);
module_exit(usb_stor_exit);


//!ZTE数据卡的模式切换
#ifdef CONFIG_ATP_USB_ADAPTOR

/*****************************************************************************
 函 数 名  : hex2num
 功能描述  : 十六进制数转数字
 输入参数  : char c  
 输出参数  : 无
 返 回 值  : int
 调用函数  : 
 被调函数  : 
指令和反馈信息格式:
*NORMAL:  9 ---->9 ;    b----->11
*UNNORMAL:        -1
 修改历史      :
  1.日    期   : 2010年7月27日
    作    者   : z00168573
    修改内容   : 新生成函数

*****************************************************************************/
int hex2num(char c)
{
	if (c >= '0' && c <= '9')
	return c - '0';
	if (c >= 'a' && c <= 'f')
	return c - 'a' + 10;
	if (c >= 'A' && c <= 'F')
	return c - 'A' + 10;
	return -1;
}

int hex2byte(const char *hex)
{
	int a, b;
	a = hex2num(*hex++);
	if (a < 0)
	return -1;
	b = hex2num(*hex++);
	if (b < 0)
	return -1;
	return (a << 4) | b;
}

/*****************************************************************************
 函 数 名  : hexstr2bin
 功能描述  : 
 输入参数  : char *hex
 输出参数  : char *buffer
 返 回 值  : int
 调用函数  : hex2byte
 被调函数  : usb_generic_switch_mode
RETURN VALUE: 
*SUCCESS:  0
*UNSUCCESS:        -1
 修改历史      :
  1.日    期   : 2010年7月27日
    作    者   : z00168573
    修改内容   : 新生成函数

*****************************************************************************/
int hexstr2bin(const char *hex, char *buffer, int len)
{
	int i = 0;
	int a = -1;
	const char *ipos = hex;
	char *opos = buffer;

    if( hex == NULL || buffer == NULL )
        return -1;

	for (i = 0; i < len; i++) {
	    a = hex2byte(ipos);
	if (a < 0)
		return -1;
	*opos++ = a;
	ipos += 2;
	}

	return 0;
}


/*****************************************************************************
 函 数 名  : usb_mode_switch
 功能描述  : USB模式切换函数
 输入参数  : struct usb_interface *interface  
 输出参数  : 无
 返 回 值  : int
 调用函数  : 
 被调函数  : 
 RETURN VALUE:
*SUCCESS:  0
*UNSUCCESS:     < 0
 修改历史      :
  1.日    期   : 2010年7月27日
    作    者   : z00168573
    修改内容   : 新生成函数

*****************************************************************************/
int usb_mode_switch( struct usb_interface *interface )
{
    struct usb_device *dev = NULL;
    usb_modeswith_t *p_dev_id = g_device_switch;    /*指向所有需要切换的数据卡*/
    char *ps_pt = NULL, *ps_mfr = NULL, *ps_sn = NULL;
    __u16 ui_found = 0, ui_flag = 0;
    
    printk( "usb_mode_switch enter.\n" );
    if( interface == NULL )
        return -1;

#define DCP_BUF_SIZE  256
    dev = interface_to_usbdev (interface);
    if( !( ps_pt = kmalloc( DCP_BUF_SIZE, GFP_KERNEL ) ) )
        return -5;
    if( !( ps_mfr = kmalloc( DCP_BUF_SIZE, GFP_KERNEL ) ) )
    {
        if( ps_pt != NULL )    
            kfree( ps_pt );
        return -5;
    }
    if( !( ps_sn = kmalloc( DCP_BUF_SIZE, GFP_KERNEL ) ) )
    {
        if( ps_pt != NULL )    
            kfree( ps_pt );
        if( ps_mfr != NULL )    
            kfree( ps_mfr );
        return -5;
    }
    memset( ps_pt, 0, DCP_BUF_SIZE );
    memset( ps_mfr, 0, DCP_BUF_SIZE );
    memset( ps_sn, 0, DCP_BUF_SIZE );
    if( dev->descriptor.iProduct > 0 )
        usb_string( dev, dev->descriptor.iProduct, ps_pt, DCP_BUF_SIZE );
    if( dev->descriptor.iManufacturer > 0 )
        usb_string( dev, dev->descriptor.iManufacturer, ps_mfr, DCP_BUF_SIZE );
    if( dev->descriptor.iSerialNumber > 0 )
        usb_string( dev, dev->descriptor.iSerialNumber, ps_sn, DCP_BUF_SIZE );
    
    printk( "vid=0x%02x, pid=0x%02x, Pt=%s, Mfr=%s, Sn=%s.\n", 
        dev->descriptor.idVendor, dev->descriptor.idProduct, ps_pt, ps_mfr, ps_sn );
    if(dev->descriptor.idVendor == 0xd219)
    {
        if(dev->descriptor.idProduct == 0x2401)
        {
        }
        else if(dev->descriptor.idProduct == 0x1701)
        {
        }
        else if(dev->descriptor.idProduct == 0x3100)
        {
        }
        else
        {
            ui_flag = p_dev_id->u16_flags;
            ui_found = ui_flag;
        }
    }
    
    if( ps_pt != NULL )    kfree( ps_pt );
    if( ps_mfr != NULL )    kfree( ps_mfr );
    if( ps_sn != NULL )    kfree( ps_sn );

    //mptk( "ui_found=0x%04x, ui_flag=0x%04x.\n", ui_found, ui_flag );
    if( ( ui_found != ui_flag ) || ( ui_flag == 0 ) )
    {
         printk( "no need switch with return -2\n" );
        return -2;
    }
    
    for( ;p_dev_id->check_mode != NULL; p_dev_id++)
    {
        if ( p_dev_id->u16_id_product == dev->descriptor.idProduct)
        {
            if( p_dev_id->check_mode != NULL && p_dev_id->check_mode( dev ) != 0 )
            {
                printk( "****************************\n" );
                printk( "***HSPA Card Switch Mode***\n" );
                printk( "****************************\n" );
                if( p_dev_id->mode_switch != NULL )
                {
                    printk( "found match device id [0x%x]\n", p_dev_id->u16_id_product);
                    printk( "send cmd [%s]\n", p_dev_id->ps_hex_str);
                    printk( "now, start switch mode....\n" );
                    p_dev_id->mode_switch( interface, p_dev_id->ps_hex_str );  /*进入切换，调用切换实施函数*/
                    if( p_dev_id->switch_complete != NULL )
                        p_dev_id->switch_complete();

                    return 0;
                }
            }
        }
    
    }


    printk( "no need switch with return -1\n" );
    return -1;
}

/*****************************************************************************
 函 数 名  : usb_generic_check_mode
 功能描述  : 检查USB的设备类型
 输入参数  : struct usb_device *dev
 输出参数  : 无
 返 回 值  : int
 调用函数  : 
 被调函数  : 
 RETURN VALUE:
*SUCCESS:  1
*UNSUCCESS:     0
 修改历史      :
  1.日    期   : 2010年7月27日
    作    者   : z00168573
    修改内容   : 新生成函数

*****************************************************************************/
int usb_generic_check_mode( struct usb_device *dev )
{
    int i_class = 0;

    printk( "src=0x%02x\n", dev->config[0].interface[0]->altsetting->desc.bInterfaceClass );
    printk( "new=0x%02x\n", dev->config->interface[0]->cur_altsetting->desc.bInterfaceClass );
    printk( "des=0x%02x\n", dev->descriptor.bDeviceClass );
    i_class = dev->config->interface[ 0 ]->cur_altsetting->desc.bInterfaceClass;
    if( i_class == USB_CLASS_MASS_STORAGE )
        return 1;

    return 0;
}

void switch_mode_bulk_callback(struct urb *urb, struct pt_regs *regs)
{
    struct completion *urb_done_ptr = (struct completion *)urb->context;

    complete(urb_done_ptr);
}

/*****************************************************************************
 函 数 名  : usb_generic_switch_mode
 功能描述  : 切换实施，将切换指令发送给USB
 输入参数  : struct usb_interface *interface,
                             char *ps_hex_str   //切换指令
 输出参数  : 无
 返 回 值  : int
 调用函数  : 
 被调函数  : usb_mode_switch
 RETURN VALUE:
*SUCCESS:  0
*UNSUCCESS:     -1
 修改历史      :
  1.日    期   : 2010年7月27日
    作    者   : z00168573
    修改内容   : 新生成函数

*****************************************************************************/
int usb_generic_switch_mode( struct usb_interface *interface, char *ps_hex_str )
{
    struct usb_device *dev = NULL;
    struct usb_host_interface *p_iface_desc = NULL;
	struct usb_endpoint_descriptor *p_endpoint = NULL;
	struct usb_endpoint_descriptor *p_bulk_out_endpoint[ MAX_NUM_PORTS ];
    struct urb *p_w_urb = NULL;
    int i = 0, i_num_bulk_out = 0;
    int i_buffer_size = 0, i_result = 0;
    unsigned char *p_ucbuf = NULL;
    struct completion urb_done;
    
    if( interface == NULL || ps_hex_str == NULL )
        return -1;

    dev = interface_to_usbdev( interface );  /*获取设备，查找端点*/
    init_completion(&urb_done);
    p_iface_desc = interface->cur_altsetting;
    for( i = 0; i < p_iface_desc->desc.bNumEndpoints; ++i )
    {
        p_endpoint = &p_iface_desc->endpoint[i].desc;
        if( ( ( p_endpoint->bEndpointAddress & 0x80 ) == 0x00) 
            &&( ( p_endpoint->bmAttributes & 3 ) == 0x02 ) ) 
        {
			/* we found a bulk out endpoint */
			printk( "found bulk out.\n" );
			p_bulk_out_endpoint[ i_num_bulk_out ] = p_endpoint;
			++i_num_bulk_out;
	}
    }

    if( i_num_bulk_out == 0 || i_num_bulk_out < 0 )
        return -1;

    for( i = 0; i < i_num_bulk_out; ++i )
    {
        p_endpoint = p_bulk_out_endpoint[ i ];
        p_w_urb = usb_alloc_urb( 0, GFP_KERNEL );
        if( p_w_urb == NULL )
        {
            break;
        }
        i_buffer_size = p_endpoint->wMaxPacketSize;
		if(i_buffer_size == 0)
        	i_buffer_size = 8192;
        p_ucbuf = kmalloc( i_buffer_size, GFP_KERNEL );
        if( p_ucbuf == NULL )
        {
            break;
        }
        usb_fill_bulk_urb( p_w_urb, dev, 
            usb_sndbulkpipe( dev, p_endpoint->bEndpointAddress ),
            p_ucbuf, i_buffer_size, switch_mode_bulk_callback, &urb_done );/*填充URB*/
        hexstr2bin( ps_hex_str, p_ucbuf, strlen( ps_hex_str ) / 2 ); /*将切换指令填充到URB*/
        p_w_urb->transfer_buffer_length = strlen( ps_hex_str ) / 2;
        i_result = usb_submit_urb( p_w_urb, GFP_ATOMIC );/*将URB提交给USB数据卡*/
	    if( i_result )
	    {
            break;
	    }
        wait_for_completion( &urb_done );
        usb_clear_halt( dev, 
            usb_sndbulkpipe( dev, p_endpoint->bEndpointAddress ) );
        
    }

    if( p_w_urb != NULL && p_w_urb->transfer_buffer != NULL )
        kfree( p_w_urb->transfer_buffer );
    if( p_w_urb != NULL )
        usb_free_urb( p_w_urb );
    return 0;
}
/*end of 添加数据卡的切换模式,从CD-Rom切换到modem模式 by z00166803 at 20100730*/

#endif

